/** @type {import('tailwindcss').Config} */
export default {
      darkMode: "class",
      theme: {
        extend: {
          "colors": {
            "brand": {
              "50": "#eff6ff",
              "100": "#dbeafe",
              "500": "#3b82f6",
              "600": "#2563eb",
              "700": "#1d4ed8",
              "800": "#1e40af",
              "900": "#1e3a8a"
            },
            "on-error": "#ffffff",
            "on-surface": "#0b1c30",
            "on-secondary-fixed-variant": "#003ea8",
            "on-secondary-fixed": "#00174b",
            "surface": "#f8f9ff",
            "surface-container-high": "#dce9ff",
            "surface-container": "#e5eeff",
            "outline": "#757684",
            "on-background": "#0b1c30",
            "secondary-fixed": "#dbe1ff",
            "secondary-fixed-dim": "#b4c5ff",
            "surface-dim": "#cbdbf5",
            "tertiary-fixed-dim": "#6bd8cb",
            "error": "#ba1a1a",
            "surface-bright": "#f8f9ff",
            "on-primary-fixed": "#001453",
            "on-secondary": "#ffffff",
            "surface-container-highest": "#d3e4fe",
            "on-tertiary": "#ffffff",
            "secondary": "#0051d5",
            "surface-tint": "#3755c3",
            "primary": "#00288e",
            "on-primary": "#ffffff",
            "primary-container": "#1e40af",
            "tertiary-fixed": "#89f5e7",
            "secondary-container": "#316bf3",
            "on-error-container": "#93000a",
            "on-secondary-container": "#fefcff",
            "on-tertiary-fixed-variant": "#005049",
            "primary-fixed-dim": "#b8c4ff",
            "surface-container-lowest": "#ffffff",
            "on-primary-fixed-variant": "#173bab",
            "on-tertiary-fixed": "#00201d",
            "background": "#f8f9ff",
            "surface-container-low": "#eff4ff",
            "on-surface-variant": "#444653",
            "inverse-on-surface": "#eaf1ff",
            "tertiary-container": "#00554e",
            "primary-fixed": "#dde1ff",
            "outline-variant": "#c4c5d5",
            "on-primary-container": "#a8b8ff",
            "error-container": "#ffdad6",
            "tertiary": "#003c36",
            "inverse-primary": "#b8c4ff",
            "surface-variant": "#d3e4fe",
            "on-tertiary-container": "#5fcdbf",
            "inverse-surface": "#213145"
          },
          "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
          },
          "spacing": {
            "space-xs": "0.25rem",
            "space-xl": "2rem",
            "space-sm": "0.5rem",
            "gutter-lg": "1.5rem",
            "margin": "1.5rem",
            "gutter": "1rem",
            "margin-mobile": "1rem",
            "space-lg": "1.5rem",
            "space-md": "1rem"
          },
          "fontFamily": {
            "display": ["Space Grotesk", "sans-serif"],
            "body-md": ["Inter"],
            "label-md": ["Inter"],
            "label-sm": ["Inter"],
            "headline-lg": ["Inter"],
            "body-sm": ["Inter"],
            "body-lg": ["Inter"],
            "label-lg": ["Inter"],
            "headline-xl": ["Inter"],
            "headline-sm": ["Inter"],
            "headline-md": ["Inter"]
          },
          "fontSize": {
            "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
            "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
            "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "600" }],
            "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
            "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.005em", "fontWeight": "400" }],
            "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
            "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "500" }],
            "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
            "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
            "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
          }
        }
      }
    }